name: CD
on:
  push:
    branches: ["develop"]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Mostrar mensaje"
        run: echo  "Hola mundo"
